Akeneo\Channel\Component\Model\Currency:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
        - Pim\Component\Catalog\Validator\Constraints\Immutable:
            properties:
                - code
